--listas de generos de perfumes
INSERT INTO tb_perfume_list (name) VALUES ('MASCULINO');
INSERT INTO tb_perfume_list (name) VALUES ('FEMININO');
INSERT INTO tb_perfume_list (name) VALUES ('COMPARTILHAVEL');

--masculino
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2018, 4.2, 'Amadeirado Aromático Masculino', 'Masculino', 'https://acdn-us.mitiendanube.com/stores/003/728/105/products/perfume_fotos_bleu-de-chanel-ff353eadca63bffaa217152001809211-1024-1024.jpg', 'Bleu de Chanel foi lançada em 2010.As notas de topo são: Toranja, Limão, Hortelã e Pimenta Rosa.', 'Bleu de Chanel de Chanel é um perfume Amadeirado Aromático Masculino','Bleu de Chanel Chanel');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2004, 4.6, 'Amadeirado Especiado Masculino', 'Masculino', 'https://puls-img.chanel.com/c_limit,w_1920/q_auto:good,dpr_auto,f_auto/1702565322050-brdesktop1440x450pxx3jpg.jpg', ' Allure Homme Sport foi lançada em 2004. O perfumista que assina esta fragrância é Jacques Polge.', 'Allure Homme Sport de Chanel é um perfume Amadeirado Especiado Masculino.','Allure Homme Sport Chanel');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2021, 4.6, 'Oriental Especiado Masculino', 'Masculino', 'https://cdn.sistemawbuy.com.br/arquivos/feb5eb39b3a2004abcc3bcd79041ba64/produtos/650796b0a5d66/20230917211544-650796b0cec53.jpg', 'The Most Wanted de Azzaro é um perfume Oriental Especiado Masculino.', 'The Most Wanted foi lançada em 2021.','The Most Wanted Azzaro');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2024, 4.2, 'Oriental Amadeirado Masculino', 'Masculino', 'https://fimgs.net/himg/o.5yPiUEICiJ9.jpg', 'MYSLF Le Parfum de Yves Saint Laurent é um perfume Oriental Amadeirado Masculino.', 'MYSLF Le Parfum foi criado por Daniela Andrier, Antoine Maisondieu e Christophe Raynaud.','MYSLF Le Parfum Yves Saint Laurent');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2023, 4.6, 'Oriental Fougére Masculino', 'Masculino', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwg2oq0Iaoi7gsS2q6udiSfhWPP4YEmz3EEA&s', 'Le Male Elixir de Jean Paul Gaultier é um perfume Oriental Fougére Masculino.', 'Esta é uma nova fragrância. Le Male Elixir foi lançada em 2023','Le Male Elixir Jean Paul Gaultier.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2018, 4.3, 'Amadeirado Especiado Masculino', 'Masculino', 'https://m.media-amazon.com/images/I/41vb-bMNRZL.jpg_BO30,255,255,255_UF900,850_SR1910,1000,0,C_PIRIOFOURANDHALF-medium,BottomLeft,30,-20_ZA57,500,900,420,420,AmazonEmber,50,4,0,0_QL100_.jpg', '212 VIP Men Party Fever de Carolina Herrera é um perfume Amadeirado Especiado Masculino.', ' 212 VIP Men Party Fever foi lançada em 2018 e é um perfume Amadeirado Especiado Masculino','212 VIP Men Party Fever.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2023, 3.5, 'Amadeirado Aromático Masculino', 'Masculino', 'https://m.media-amazon.com/images/I/41bgIntFDTL._UF1000,1000_QL80_.jpg', 'Phantom foi criado por Anne Flipo, Dominique Ropion, Loc Dong e Juliette Karagueuzoglou. As notas de topo são: Lavanda, Raspas de Limão e Limão de Amalfi.', 'Phantom de Rabanne é um perfume Amadeirado Aromático Masculino.','Phantom Rabanne.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2012, 4.5, 'Oriental Amadeirado Masculino', 'Masculino', 'https://www.giraofertas.com.br/wp-content/uploads/2019/07/Noir-Tom-Ford-Eau-de-Parfum-04.jpg', ' O perfumista que assina esta fragrância é Olivier Gillotin. As notas de topo são: Violeta, Pimenta Rosa, Alcarávia, Bergamota e Verbena.', 'Noir de Tom Ford é um perfume Oriental Amadeirado Masculino.','Noir Tom Ford.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2025, 4.3, 'Amadeirado Especiado Masculino', 'Masculino', 'https://epocacosmeticos.vteximg.com.br/arquivos/ids/807277-450-450/perfume-valentino-born-in-roma-masculino-eau-de-parfum-intense--1-.jpg.jpg?v=638881008072270000', 'Valentino Uomo Born in Roma foi criado por Antoine Maisondieu e Guillaume Flavigny. As notas de topo são: Notas Minerais, Folha de Violeta e Sal. As notas de coração são: Gengibre e Sálvia. As notas de fundo são: Notas Amadeiradas e Vetiver.', 'Valentino Uomo Born in Roma de Valentino é um perfume Amadeirado Especiado Masculino.','Valentino Uomo Born in Roma Valentino.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (1994, 4.2, 'Aquático Amadeirado Masculino', 'Masculino', 'https://m.media-amazon.com/images/I/5105B4XtR6L._AC_SX679_.jpg', 'O perfumista que assina esta fragrância é Jacques Cavallier Belletrud. As notas de topo são: Yuzu, Limão, Bergamota, Lúcia-lima, Mandarina, Cipreste, Calone, Coentro, Sálvia e Estragão.', 'L''Eau d''Issey Pour Homme de Issey Miyake é um perfume Aquático Amadeirado Masculino.','L''Eau d''Issey Pour Homme Issey Miyake.');

--feminino
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2023, 4.0, 'Oriental Floral Feminino.', 'Feminino', 'https://m.media-amazon.com/images/I/61vwxTQk0tL._AC_SX342_SY445_QL70_ML2_.jpg', 'Good Girl foi criado por Louise Turner e Quentin Bisch.', 'Good Girl de Carolina Herrera é um perfume Oriental Floral Feminino.','Good Girl Carolina Herrera.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2017, 3.9, 'Chipre Floral Feminino.', 'Feminino', 'https://m.media-amazon.com/images/I/51rAIP1wi9L.jpg', 'Scandal foi criado por Daphné Bugey, Fabrice Pellegrin e Christophe Raynaud. As notas de topo são: Laranja Sanguínea e Mandarina. ', 'Scandal de Jean Paul Gaultier é um perfume Chipre Floral Feminino.','Scandal Jean Paul Gaultier.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2017, 4.4, 'Chipre Compartilhável.', 'Feminino', 'https://neeche.vteximg.com.br/arquivos/ids/157717-1000-1000/Nishane-Hacivat-Extrait-de-Parfum---Perfume-Unissex-100ml---8681008055180.jpg?v=637537608324800000', 'O perfumista que assina esta fragrância é Jorge Lee. As notas de topo são: Abacaxi, Toranja e Bergamota. As notas de coração são: Cedro, Patchouli e Jasmim.', 'Hacivat de Nishane é um perfume Chipre Compartilhável.','Hacivat Nishane.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2023, 4.1, 'Oriental Baunilha.', 'Feminino', 'https://www.sephora.com.br/dw/image/v2/BFJC_PRD/on/demandware.static/-/Sites-masterCatalog_Sephora/pt_BR/dwa4e5d0fd/images/hi-res-BR/8057971183739_1_1000px.jpg?sw=1200&sh=1200&sm=fit.', 'O perfumista que assina esta fragrância é Olivier Cresp. A nota de topo é Limão Cristalizado. As notas de coração são: Panacotta, Flor de Laranjeira e Rum. A nota de fundo é Baunilha.', 'Devotion de Dolce&Gabbana é um perfume Oriental Baunilha Feminino.','Devotion Dolce&Gabbana.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2018, 4.2, 'Oriental Baunilha Compartilhável.', 'Feminino', 'https://www.sephora.com.br/dw/image/v2/BFJC_PRD/on/demandware.static/-/Sites-masterCatalog_Sephora/pt_BR/dw7d5d6107/images/hi-res-BR/Frag/QUELE/6291106039894_1000px.jpg?sw=1200&sh=1200&sm=fit', ' O perfumista que assina esta fragrância é Gabriela Chelariu. As notas de topo são: Orquídea Baunilha e Jasmim. As notas de coração são: Açúcar mascavo e Fava Tonka. As notas de fundo são: Âmbar, Madeira de Âmbar, Almíscar e Patchouli.', 'Vanilla 28 de Kayali Fragrances é um perfume Oriental Baunilha Compartilhável.','Vanilla 28 Kayali Fragrances.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2023,4.2, 'Oriental Baunilha Compartilhável.', 'Feminino', 'https://fimgs.net/mdimg/perfume/o.64757.jpg', 'O perfumista que assina esta fragrância é Silvia Martinelli. A nota de topo é Caramelo. As notas de coração são: Cumarina e Mel.','Bianco Latte Giardini Di Toscana','Bianco Latte Giardini Di Toscana');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2024,4.1, 'Oriental Floral Feminino.', 'Feminino', 'https://www.sephora.com.br/dw/image/v2/BFJC_PRD/on/demandware.static/-/Sites-masterCatalog_Sephora/pt_BR/dw7c4ffd8a/images/hi-res-BR/Frag/Nova%20pasta/Maria%20Helena%202.0/8011003891061.png?sw=1200&sh=1200&sm=fit', 'As notas de topo são: Especiarias, Pimenta Rosa e Groselha Preta. As notas de coração são: Caramelo, Tuberosa e Lírio-do-Vale. As notas de fundo são: Âmbar, Sândalo, Baunilha, Akigalawood e Orquídea.','As notas de coração são: Caramelo, Tuberosa e Lírio-do-Vale. As notas de fundo são: Âmbar, Sândalo, Baunilha, Akigalawood e Orquídea.','Crystal Noir Parfum Versace.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2004,4.3, 'Floral Amadeirado Almiscarado Feminino.', 'Feminino', 'https://www.sephora.com.br/dw/image/v2/BFJC_PRD/on/demandware.static/-/Sites-masterCatalog_Sephora/pt_BR/dwcb3f2775/images/hi-res-BR/_D65D7D73-E430-459F-AA78-3ACE46C95C33__packshot_moschino_i_love_love_50ml-500px.jpg?sw=400&sh=400&sm=fit', 'O perfumista que assina esta fragrância é Olivier Cresp. As notas de topo são: Toranja, Laranja, Limão e Groselha Vermelha.',' O perfumista que assina esta fragrância é Olivier Cresp. As notas de topo são: Toranja, Laranja, Limão e Groselha Vermelha. As notas de coração são: Cana-de-Açúcar, Pau de Lagoa, Lírio-do-Vale, Rosa Chá e Canela.','Cheap & Chic I Love Love de Moschino');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2021,4.2, 'Floral Frutado Feminino.', 'Feminino', 'https://neeche.vteximg.com.br/arquivos/ids/165456-1000-1000/Parfums-de-Marly---DELINA-LA-ROSE-3700578500786.jpg?v=638893778215800000', 'O perfumista que assina esta fragrância é Quentin Bisch. As notas de topo são: Lichia, Pera, Bergamota e Pimenta Rosa. As notas de coração são: Rosa Turca, Peônia, Notas Aquosas e Notas Florais.','O perfumista que assina esta fragrância é Quentin Bisch. As notas de topo são: Lichia, Pera, Bergamota e Pimenta Rosa. As notas de coração são: Rosa Turca, Peônia, Notas Aquosas e Notas Florais.','Delina La Rosée Parfums de Marly');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2023,3.9, ' Floral Frutado Feminino.', 'Feminino', 'https://neeche.vteximg.com.br/arquivos/ids/165426-520-520/2208_MARLY_VALAYA_bottle-only.1--1-.jpg?v=638893758617430000', ' O perfumista que assina esta fragrância é Quentin Bisch. As notas de topo são: Aldeídos, Pêssego Branco, Bergamota e Mandarina. As notas de coração são: Flor de Laranjeira, Lírio-do-Vale, Petalia, Nympheal™, Vetiver e Uva do Oregon.','O perfumista que assina esta fragrância é Quentin Bisch. As notas de topo são: Aldeídos, Pêssego Branco, Bergamota e Mandarina. As notas de coração são: Flor de Laranjeira, Lírio-do-Vale, Petalia, Nympheal™, Vetiver e Uva do Oregon.','Valaya Parfums de Marly');


--compartilhavel
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (1995, 4.3, 'Amadeirado Floral Almiscarado Compartilhável.', 'Compartilhável', 'https://images.tcdn.com.br/img/img_prod/1053276/creed_millesime_imperial_edp_100ml_31_1_e271595dce9a9a2fef763706a2af691d.jpg', 'O perfumista que assina esta fragrância é Jorge Lee. As notas de topo são: Abacaxi, Toranja e Bergamota. As notas de coração são: Cedro, Patchouli e Jasmim.', 'Hacivat de Nishane é um perfume Chipre Compartilhável.','Black Orchid Tom Ford.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2019, 3.8, 'Oriental Compartilhável.', 'Compartilhável', 'https://anbeauty.vtexassets.com/arquivos/ids/177910-1200-1200?width=1200&height=1200&aspect=true', 'Erba Pura foi criado por Christian Carbonnel e Laura Santander. As notas de topo são: Laranja Siciliana, Bergamota da Calábria e Limão Siciliano.', 'Erba Pura de Xerjoff é um perfume Oriental Compartilhável.','Erba Pura Xerjoff.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2021, 4.2, 'Amadeirado Floral Almiscarado.', 'Compartilhável', 'https://acdn-us.mitiendanube.com/stores/001/216/674/products/musk-b4f84096a2d0159bfe17206397178371-480-0.webp', 'Musk Therapy é um floral almiscarado com toque cítrico cremoso, criado pra acalmar, elevar o humor e viciar. Um verdadeiro “perfume-terapia”, com notas suaves, sofisticadas e um fundo confortável que fixa na pele como um carinho.', 'Musk Therapy de Initio Parfums Prives é um perfume Amadeirado Floral Almiscarado Compartilhável.','Musk Therapy Initio Parfums Prives.');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2011, 3.8, 'Amadeirado Aromático Compartilhável.', 'Compartilhável', 'https://acdn-us.mitiendanube.com/stores/001/487/363/products/0ap-0003-004_zoom11-8f35e80b27e32ec32b16915234785894-640-0.webp', 'Imagine-se sentado na solidão nas amplas e acidentadas planícies do oeste americano, com a luz do fogo no rosto e o céu noturno azul índigo acima. Não há nada por perto, exceto o vento suave do deserto. Você. Ser. Livre','Santal 33 de Le Labo é um perfume Amadeirado Aromático Compartilhável. Santal 33 foi lançada em 2011.','Santal 33 Le Labo');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2019, 4.3, 'Oriental Floral Compartilhável.', 'Compartilhável', 'https://acdn-us.mitiendanube.com/stores/001/216/674/products/nishane-ani1-d7e33dd5e0b232c8c816228312973201-1024-1024.webp', 'O perfumista que assina esta fragrância é Cecile Zarokian As notas de topo são Gengibre, Bergamota, Pimenta rosa e Notas Verdes as notas de coração são Cardamomo, Cassis ou groselha preta e Rosa Turca as notas de fundo são Baunilha, Sândalo, Benjoim, Cedro, Patchouli ou Oriza, Âmbar Cinzento e Almíscar','Ani de Nishane é um perfume Oriental Floral Compartilhável. Ani foi lançada em 2019.','Ani Nishane');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2007, 4.4, 'Cítrico Compartilhável.', 'Compartilhável', 'https://fimgs.net/mdimg/perfume/o.899.jpg','Virgin Island Water 2007 foi criado por Olivier Creed e Erwin Creed. As notas de topo são: Coco, Lima, Bergamota branca e Mandarina Siciliana.','Virgin Island Water 2007 de Creed é um perfume Cítrico Compartilhável. ','Virgin Island Water 2007 Creed');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2015, 4.3, 'Amadeirado Aromático Compartilhável.', 'Compartilhável', 'https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw26fbcbf5/Y0768550/Y0768550_F076855009_E01_ZHC.jpg?sw=1280', 'Desenvolvido a partir de favas-tonka venezuelanas, esta composição do Perfumista-Criador de Dior, François Demachy, literalmente encanta os sentidos.','Atraído pela "sedução imediata" desse ingrediente, François Demachy quis criar uma representação personalizada da fava-tonka.','Fève Délicieuse');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2016, 4.4, 'Oriental Compartilhável.', 'Compartilhável', 'https://acdn-us.mitiendanube.com/stores/001/216/674/products/effect1-27ae56c991e50448f116807989432408-1024-1024.webp', 'Uma harmonia apaixonante de Tabaco, Baunilha, Rum e Canela revela emoções profundas, levando você a um estado de jogo ousado.','Side Effect de Initio Parfums Prives é um perfume Oriental Compartilhável.','Side Effect Initio Parfums Prives');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (1995, 4.3, 'Amadeirado Floral Almiscarado.', 'Compartilhável', 'https://themgstore.com.br/wp-content/uploads/2025/02/15172370470-3508441001039-millesime-imperial-600x600.png', 'Uma essência revigorante para homens e mulheres. Uma atmosfera de pomares de citros e exuberante paisagem de um palácio à beira-mar, na Sicília.','Millésime Impérial de Creed é um perfume Amadeirado Floral Almiscarado Compartilhável.','Millésime Impérial Creed ');
INSERT INTO tb_perfumes (release_year, score, fragance_notes, genre, img_url, long_description, short_description, title) VALUES (2017, 4.1, 'Oriental Baunilha Compartilhável.', 'Compartilhável', 'https://neeche.vteximg.com.br/arquivos/ids/162830-1000-1000/TF-Vanille-Fatale-EDP_888066150491_-1-.jpg?v=638479306152870000', 'O perfumista que assina esta fragrância é Yann Vasnier. As notas de topo são: Rum, Mirra, Olíbano, Açafrão, Coentro, Laranja e Lima. ','Vanille Fatale Tom Ford.','Vanille Fatale Tom Ford');


--povoando as listas com os perfumes - masculinos
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 1, 0,'Bleu de Chanel Chanel.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 2, 1,'Allure Homme Sport Chanel.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 3, 2,'The Most Wanted Azzaro.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 4, 3,'MYSLF Le Parfum Yves Saint Laurent.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 5, 4,'Le Male Elixir Jean Paul Gaultier.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 6, 5,'212 VIP Men Party Fever.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 7, 6,'Phantom Rabanne.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 8, 7,'Noir Tom Ford.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 9, 8,'Valentino Uomo Born in Roma Valentino.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (1, 10, 9,'Issey Miaky Pour Homme Issey Miyake.');


--povoando as listas com os perfumes - femininos
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 1, 0,'Good Girl Carolina Herrera.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 2, 1,'Scandal Jean Paul Gaultier.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 3, 2,'Hacivat Nishane.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 4, 3,'Devotion Dolce&Gabbana.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 5, 4,'Vanilla 28 Kayali Fragrances.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 6, 5,'Bianco Latte Giardini Di Toscana.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 7, 6,'Crystal Noir Parfum Versace.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 8, 7,'Cheap & Chic I Love Love de Moschino.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 9, 8,'Delina La Rosée Parfums de Marly.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (2, 10, 9,'Valaya Parfums de Marly.');


--povoando as listas com os perfumes - compartilhaveis
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 1, 0,'Black Orchid Tom Ford.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 2, 1,'Erba Pura Xerjoff.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 3, 2,'Musk Therapy Initio Parfums Prives.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 4, 3,'Santal 33 Le Labo.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 5, 4,'Ani Nishane.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 6, 5,'Virgin Island Water 2007 Creed.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 7, 6,'Fève Délicieuse.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 8, 7,'Side Effect Initio Parfums Prives.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 9, 8,'Millésime Impérial Creed.');
INSERT INTO tb_belonging (list_id, perfume_id, position,title) VALUES (3, 10, 9,'Vanille Fatale Tom Ford.');